// <auto-generated />
using _4MAT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace _4MAT.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171128100012_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("_4MAT.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BluePlayerId");

                    b.Property<int>("BlueScore");

                    b.Property<DateTime>("KickOff");

                    b.Property<int>("Outcome");

                    b.Property<Guid?>("RedPlayerId");

                    b.Property<int>("RedScore");

                    b.HasKey("Id");

                    b.HasIndex("BluePlayerId");

                    b.HasIndex("RedPlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("_4MAT.Data.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_4MAT.Data.Game", b =>
                {
                    b.HasOne("_4MAT.Data.Player", "BluePlayer")
                        .WithMany()
                        .HasForeignKey("BluePlayerId");

                    b.HasOne("_4MAT.Data.Player", "RedPlayer")
                        .WithMany()
                        .HasForeignKey("RedPlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
